### ISSUE TITLE
Error when I want to get pager data by passing parameters

### ISSUE THREAD

**Issue by weixiongli** [LinqToDB4iSeries/Linq2DB4iSeries#32]
Thanks for your effort in advance.
 It does not work on me 
Exception:
Cause . . . . . :   The keyword BY was not expected here.  A syntax error was detected at keyword BY.  The partial list of valid tokens is FOR USE SKIP WAIT WITH FETCH LIMIT ORDER UNION EXCEPT OFFSET. This list assumes that the statement is correct up to the unexpected keyword.  The error may be earlier in the statement but the syntax of the statement seems to be valid up to this point. Recovery  . . . :   Examine the SQL statement in the area of the specified keyword.  A colon or SQL delimiter may be missing. SQL requires reserved words to be delimited when they are used as a name. Correct the SQL statement and try the request again.

Code does not work:
`  string name = "001";
            var s2 = db.SERIs
                .Where(p => p.HTSTKL == name)
                .OrderByDescending(p => p.HTADAT)
                .Select(x => x.HTSERN)
                .Distinct()
                .Skip(0)
                .Take(3);
var s3 = s2.ToList();`

But it works on me if I do not use variable name:
`              var s2 = db.SERIs
                .Where(p => p.HTSTKL == "001")
                .OrderByDescending(p => p.HTADAT)
                .Select(x => x.HTSERN)
                .Distinct()
                .Skip(0)
                .Take(3);
 var s3 = s2.ToList();`

I've tried to set versions, but still doesn't work, please help me out
<add name="iSeriesProvider" type="LinqToDB.DataProvider.DB2iSeries.DB2iSeriesFactory, LinqToDB.DataProvider.DB2iSeries"   MinVer="7.1.38" />

Also let me add stackTrace to make it clear

   at IBM.Data.DB2.iSeries.iDB2Exception.throwDcException(MpDcErrorInfo mpEI, MPConnection conn)
   at IBM.Data.DB2.iSeries.iDB2Command.reportDCError(Int32 rc)
   at IBM.Data.DB2.iSeries.iDB2Command.Prepare()
   at IBM.Data.DB2.iSeries.iDB2Command.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1181
   at LinqToDB.Data.DataConnection.ExecuteReader() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1174
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 445
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__9`1.MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 320
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by RoyC-Retail-Assist** [comment]
Please can you post the SQL that each version generates.

**Comment by weixiongli** [comment]
Thanks for your rapid response.

```
-- Conn DB2.iSeries DB2iSeries7_2
DECLARE @name iDB2VarGraphic(3) -- String
SET     @name = '001'

SELECT
	p.HTSERN,
	Min(p.HTADAT) as oby
FROM
	CMSDATCN.SERI p
WHERE
	p.HTSTKL = @name
GROUP BY
	p.HTSERN
ORDER BY
	Min(p.HTADAT) DESC
OFFSET 0 ROWS FETCH FIRST 3 ROWS ONLY 

```
 and 

```
-- Conn DB2.iSeries DB2iSeries
DECLARE @name iDB2VarGraphic(3) -- String
SET     @name = '001'

SELECT *
FROM
(
	SELECT
		t.*,
		ROW_NUMBER() OVER
		(
			ORDER BY
				oby DESC
		) as rn
	FROM
	(
		SELECT
			p.HTSERN,
			Min(p.HTADAT) as oby
		FROM
			CMSDATCN.SERI p
		WHERE
			p.HTSTKL = @name
		GROUP BY
			p.HTSERN
		ORDER BY
			Min(p.HTADAT) DESC
	) t
) t1
WHERE
	t1.rn BETWEEN 1 AND 3
```

**Comment by weixiongli** [comment]
> Please can you post the SQL that each version generates.
Added , please check it out thanks, please contact with me if you need anything else.

**Comment by weixiongli** [comment]
I addressed this issue by adding new line
`
				db.InlineParameters = true;`
Maybe it is useful to someone else since there are not too many As400 developers.

Thanks for your efforts and it helps me a lot.
